### ISSUE TITLE
DiffPose is not compatiable with the DiffDRR 0.3.10 or later

### ISSUE THREAD

**Issue by YongzeYang** [eigenvivek/DiffPose#13]
Dear @eigenvivek,

I found some compaticility issues. DiffPose cannot run if the version of DiffDRR is 0.3.10 or later. 

I noticed that you have refactored RigidTransofrm in the rencent version update of DiffDRR, and removed most of the functions in utils. However, some functions such as convert need to be imported in DiffPose.

To solve this problem, I rolled back the version of DiffPose to 0.3.9. Although no errors were found during importing, when running some jupyter files in '/notebooks/', I found another problem: "'RigidTransform' object has no attribute 'dtype'". 

I wonder if there are any solutions to these problems? I would be grateful if you could reply soon.

Best wishes,
Yongze

**Comment by eigenvivek** [comment]
Hi @YongzeYang , thank you for raising this issue. I am migrating the code in `DiffPose` to work with the latest version of `DiffDRR`. For now, you can try working with the `refactor-se3` branch - this has the most updated code, which I will merge with main once I'm sure there's no bugs

For more details see
- https://github.com/eigenvivek/DiffPose/issues/7
- https://github.com/eigenvivek/DiffPose/issues/12

**Comment by eigenvivek** [comment]
Thanks for the issue, I updated the environment.yml to hopefully help others avoid this issue while I finish patching the code.

**Comment by JamesTsien11** [comment]
> Dear @eigenvivek,
> 
> I found some compaticility issues. DiffPose cannot run if the version of DiffDRR is 0.3.10 or later.
> 
> I noticed that you have refactored RigidTransofrm in the rencent version update of DiffDRR, and removed most of the functions in utils. However, some functions such as convert need to be imported in DiffPose.
> 
> To solve this problem, I rolled back the version of DiffPose to 0.3.9. Although no errors were found during importing, when running some jupyter files in '/notebooks/', I found another problem: "'RigidTransform' object has no attribute 'dtype'".
> 
> I wonder if there are any solutions to these problems? I would be grateful if you could reply soon.
> 
> Best wishes, Yongze

Hello Yang， 
Have you solved this problem？

Best wishes！
