### ISSUE TITLE
AutoExecutor.map_array (main, id_numbers) code is not running.

### ISSUE THREAD

**Issue by ryukyungjoon** [eigenvivek/DiffPose#18]
AutoExecutor.map_array (main, id_numbers) code is not running.
I tried to output random characters as a printf function inside the main function to see if it is entering the function, but no characters are output and the entire code ends normally.

May I know how to enter the main sentence and learning my data in train.py?
Thank you.

main function enter before
![image](https://github.com/eigenvivek/DiffPose/assets/48307173/89c8aabc-2042-4b0f-82ba-6ce0f504d1aa)

main function inner
![image](https://github.com/eigenvivek/DiffPose/assets/48307173/e93f814a-f680-4572-b14a-f53e32ec661f)

whole code result console
![image](https://github.com/eigenvivek/DiffPose/assets/48307173/fe55d2cd-70f0-4b89-a663-da3b6347aba9)

**Comment by eigenvivek** [comment]
Hi @ryukyungjoon, do you have `submitit` installed?

**Comment by ryukyungjoon** [comment]
I identified the problem and solved the cause.
There was a lack of understanding of the DiffPose project.
I don't have enough hardware resources to run multi-threads.
Thank you for your response.

**Comment by eigenvivek** [comment]
No problem, happy to hear you figured it out!
