### ISSUE TITLE
How to build a stable Conda environment for running Diffpose

### ISSUE THREAD

**Issue by 98zhenyu** [eigenvivek/DiffPose#20]
1. Please, what version of Python does the environment require to run for Diffpose? 
2. Currently, I've built a Conda environment with Python 3.10, but when I try to directly 'pip install diffpose', it throws an error due to missing PyTorch3D dependency. 
3. Is it correct for me to reconfigure the environment by installing 'environment.yml' from Diffpose, like 'pip install -e .'?

**Comment by eigenvivek** [comment]
Hi @98zhenyu , thanks for letting me know. It should work to install from source like this:
```
mamba create -f environment.yml
mamba activate diffpose
pip install -e .
```

**Comment by pobi123** [comment]
> Hi @98zhenyu , thanks for letting me know. It should work to install from source like this:
> 
> ```
> mamba create -f environment.yml
> mamba activate diffpose
> pip install -e .
> ```

Hello, what should I do if an error occurs when executing condacreate -f environment.yml?

**Comment by eigenvivek** [comment]
Hi @pobi123 , what errors are you getting?

**Comment by eigenvivek** [comment]
sorry the first line should've said `mamba env create -f environment.yml`
