### ISSUE TITLE
pytorch3d missing error

### ISSUE THREAD

**Issue by hws203** [eigenvivek/DiffPose#25]
I cannot run owing to pytorch3d module missing.  how to solve this issue?

**Comment by eigenvivek** [comment]
Hi @hws203, make sure you use `diffdrr=0.3.9` with `diffpose`. That version of `diffdrr` still has a dependency for `pytorch3d`.

**Comment by 00maarten00** [comment]
Using pip to install all the libraries it seems to not be able to find pytorch. Torch 2.2.2 is installed however and diffdrr 0.3.9 is also installed. The following error is being produced:
ERROR: Could not find a version that satisfies the requirement pytorch3d (from diffpose) (from versions: none)
ERROR: No matching distribution found for pytorch3d

version: Python 3.11.9
