### ISSUE TITLE
About detector target points

### ISSUE THREAD

**Issue by lixinxin9703** [eigenvivek/DiffPose#28]
diffdrr version 0.3.9

`target[...,2] -= self.x0
target[...,1] -= self.y0
`
Why is it not adding but subtracting?

**Comment by eigenvivek** [comment]
Hi @lixinxin9703 just a convention choice. In DiffDRR, the detector plane (in 1D) runs from [0, ..., N]. To align the detector plane with the center of the principal ray, we subtract N // 2. To further adjust with a non-zero principal point, we subtract `x0`. You could equivalently define all of these operations with addition.
