### ISSUE TITLE
DRR image abnormal

### ISSUE THREAD

**Issue by ryukyungjoon** [eigenvivek/DiffPose#31]
![image](https://github.com/user-attachments/assets/b5550c51-2a33-456c-b96e-69704e0e2d9e)
DRR images show the abnormal results.
I run the Deepfluoro/train.py
How to can i fix it?

p.s. This volume data is my custom spine data

**Comment by eigenvivek** [comment]
Hi, this looks like a spacing issue. Which version of DiffDRR are you using? If it’s the latest version, can you confirm your affine matrix has the proper spacing?

**Comment by ryukyungjoon** [comment]
Hi, Thank you answer to me.
My DiffDRR Version is 0.3.9. 
What should I do? please tell me.
Thank you Vivek.

**Comment by eigenvivek** [comment]
Closed by #34
