### ISSUE TITLE
Train one model for 6 specimen

### ISSUE THREAD

**Issue by legendjack** [eigenvivek/DiffPose#36]
Hi Vivek,

Thank you for your work.

I ran your code on a GPU. I wonder if I run this command `cd experiments/deepfluoro & srun python train.py`, will it train 6 models for 6 specimen. So how to train a single model for 6 specimen.

And I ran `evaluate.py`, the model got a rough registration result. In `register.py`, it performed a gradient descent optimization after model prediction, and the result is much more precise. Is it possiable to train a model to get a precise result directly?

I am a beginner in deep learning registration, look forward to your reply. Thank you.

**Comment by eigenvivek** [comment]
Hi @legendjack to train a single model for subject 6, you could replace this line

https://github.com/eigenvivek/DiffPose/blob/b3937c4575a0ad092a7ac5b4e661a4fb1b06fc3f/experiments/deepfluoro/evaluate.py#L70

with `id_numbers = [6]`.

The fact that the deep learning model's prediction is worse than the output of an iterative optimization algorithm is a well-known phenomena in medical image registration. In general, deep learning-based registration are never as accurate as iterative methods. There's a lot of literature about ways to close that gap, but so far, there's no universal solution.
