### ISSUE TITLE
Is there a reason why DiffPose model only learns about one specific?

### ISSUE THREAD

**Issue by ryukyungjoon** [eigenvivek/DiffPose#37]
HI, Vivek
I'm getting a lot of help from you, thank you.
The diffpose model seems to learn about one specimen. I'm wondering if there's a special reason first.

Thank you for your answer.

**Comment by eigenvivek** [comment]
Hi @ryukyungjoon we learn a model for a specific subject such that the model is hyperaccurate for that patient. In the context of surgery, this is akin to overfitting on the specific patient about to undergo a procedure. In that usecase, you don't care if the model generalizes to new patients, only that it's accurate for the current patient.
