### ISSUE TITLE
Question about running time

### ISSUE THREAD

**Issue by yuyouxixi** [eigenvivek/DiffPose#41]
Hi, thank you for your wonderful work!

I am a little confused about the Time shown in the table1 in the paper (2.2±1.2). Does this time refer to the total of inference time and test-time optimization? When I run register.py for deepfluoro dataset, it takes about 30 seconds to optimize each X-ray image on the 4090 GPU. This has left me confused about what exactly the "running time" refers to. 

By the way, after running register.py, I obtained many CSV files containing various metrics. Does the mTRE metric mentioned in the paper refer to the 'fiducial' metric among them?

I hope you can help clarify my confusion! Thank you very much!

**Comment by eigenvivek** [comment]
Hi @yuyouxixi , runtime refers to how long the test-time optimization steps take for a single X-ray. So this doesn't include loading the neural network, medical images, and DRR module or the time to get the initial pose estimate from the neural network. However, 30 sec seems very long for all that. In my testing, I found that 2080Tis were faster than A6000s, so perhaps its a hardware issue? But again, seems very slow. 

And yes `fiducial` refers to mTRE (but see #27).
