### ISSUE TITLE
Couldn't find some functions

### ISSUE THREAD

**Issue by erich-r** [eigenvivek/DiffPose#45]
Hello Vivek,
thanks for sharing your interesting work.
I've tried to import some functions in order to play with `DiffPose`, however, when I try to import these packages:
```

from diffdrr.drr import DRR
from diffdrr.metrics import MultiscaleNormalizedCrossCorrelation2d
from torchvision.transforms.functional import resize
from tqdm import tqdm

from diffpose.calibration import RigidTransform, convert
from diffpose.deepfluoro import DeepFluoroDataset, Evaluator, Transforms
from diffpose.metrics import DoubleGeodesic, GeodesicSE3
from diffpose.registration import PoseRegressor, SparseRegistration
```

`ImportError: cannot import name 'convert' from 'diffdrr.utils'`

it raises an error, stating that in `diffdrr.utils `there is no `convert` function (I also have this error with `make_xray` function).
Am I missing something ? 
Best regards

**Comment by eigenvivek** [comment]
hi @erich-r do the packages you have installed match the versions in [`environment.yml`](https://github.com/eigenvivek/DiffPose/blob/main/environment.yml)?

**Comment by eigenvivek** [comment]
closing for now, feel free to reopen if you have more questions!

**Comment by erich-r** [comment]
Hi Vivek, I checked the version of diffdrr library, I noticed I had another version (0.4.X), so I removed it and installed the version specified in the .yml file.
output of `conda list -n [env]`:
```

# Name                    Version                   Build  Channel
...
diffdrr                   0.3.9                    pypi_0    pypi
diffpose                  0.0.1                    pypi_0    pypi
...
```

Now if I try to import the functions specified in the first post, I get this error:
`ModuleNotFoundError: No module named 'diffdrr.pose' `

<img width="636" alt="immagine" src="https://github.com/user-attachments/assets/f73f1a45-5c2e-4cba-84eb-776f608d61f9" />

**Comment by erich-r** [comment]
ok i had another version of `diffdrr` , I installed the version specified in the `.yml` file and now I am able to import all those modules. thanks!
