### ISSUE TITLE
Using Diffpose for with a simple API for custom training and inference

### ISSUE THREAD

**Issue by amarbanerjee23** [eigenvivek/DiffPose#8]
Hi,
This is a great work and I'd like to try it out on my custom data. However, not able to perform training/inference/visualization of results on custom data. Could anyone please guide me towards using a simple API to train/infer and visualize inferred results?

Thanks in advance,
Amar

**Comment by eigenvivek** [comment]
Hi Amar, thank you. Unfortunately, there isn't an easy-to-use API for training DiffPose on new data at the moment. For now, the most straightforward approach would be to modify the [training](https://github.com/eigenvivek/DiffPose/blob/main/experiments/deepfluoro/train.py) and [evaluation](https://github.com/eigenvivek/DiffPose/blob/main/experiments/deepfluoro/evaluate.py) scripts to use your datasets.

This would be quite a lot of work. As a first step, I would recommend adapting the [optimizers tutorial in DiffDRR](https://vivekg.dev/DiffDRR/tutorials/optimizers.html) to work with your data. This will take a lot less time and should give you a good understanding of how to use DiffDRR. From there, adapting to DiffPose should be much easier.

Feel free to let me know if you run into any other difficulties, happy to help!

**Comment by eigenvivek** [comment]
Closing this, feel free to reopen if I can help in any other way!
