### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by springXIACJ** [eigenvivek/DiffPose#9]
I have a question about getting the volume
![image](https://github.com/eigenvivek/DiffPose/assets/37493123/fe7bdfec-8a63-4749-a798-7d56b4c8037b)
I understood the operation the swapaxes of the volume, but I don’t understand why [::-1] is needed.

**Comment by eigenvivek** [comment]
Hi @springXIACJ , `[::-1]` is applied to reverse the x-axis. There's a lot of ambiguity in how to orient a cube of CT data in physical space. Reversing the x-axis was determined through experimentation - it was necessary to make the poses from the `DeepFluoro` dataset match the renderings I was getting from `DiffDRR`.

Ideally, I would like to build a canonical orientation system into `DiffDRR` (i.e., something that mimics the orientation used by Slicer or ITK-Snap when you load a CT in it). But that's [a future work](https://github.com/eigenvivek/DiffDRR/issues/192)!

**Comment by eigenvivek** [comment]
Closing this, feel free to reopen if you are having any issues with your data!
